---

# Debian family installation tasks

- name: 'INSTALL | APT | Install system prerequisites'
  become: True
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    cache_valid_time: "{{ qgis_server_repository_cache_valid_time }}"
  loop: "{{ qgis_server_system_prerequisites }}"


- name: 'INSTALL | APT | Configure repositories GPG keys'
  become: True
  apt_key:
    id: "{{ item.id | default(omit) }}"
    keyserver: "{{ item.keyserver | default(omit) }}"
    url: "{{ item.url | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ qgis_server_repositories_keys }}"


- name: 'INSTALL | APT | Configure repositories'
  become: True
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ qgis_server_repositories }}"


- name: 'INSTALL | APT | Install QGIS Server packages'
  become: True
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    cache_valid_time: "{{ qgis_server_repository_cache_valid_time }}"
  loop: "{{ qgis_server_system_packages }}"
